# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dlnb',
                'doc_host': 'https://Iamalos.github.io',
                'git_url': 'https://github.com/Iamalos/dlnb',
                'lib_path': 'dlnb'},
  'syms': {'dlnb.core': {'dlnb.core.foo': ('core.html#foo', 'dlnb/core.py')}}}