# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dlnb',
                'doc_host': 'https://Iamalos.github.io',
                'git_url': 'https://github.com/Iamalos/dlnb',
                'lib_path': 'dlnb'},
  'syms': { 'dlnb.core': { 'dlnb.core.HyperParameters': ('core.html#hyperparameters', 'dlnb/core.py'),
                           'dlnb.core.HyperParameters.save_hyperparameters': ( 'core.html#hyperparameters.save_hyperparameters',
                                                                               'dlnb/core.py'),
                           'dlnb.core.Module': ('core.html#module', 'dlnb/core.py'),
                           'dlnb.core.init_cnn': ('core.html#init_cnn', 'dlnb/core.py')}}}